// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIcFbvoZ5hrMeAS1e3ewgPvZhVj7GVioc',
    appId: '1:841967297444:web:6d23d4fba3406d4bf0d731',
    messagingSenderId: '841967297444',
    projectId: 'classic-18beb',
    authDomain: 'classic-18beb.firebaseapp.com',
    storageBucket: 'classic-18beb.firebasestorage.app',
    measurementId: 'G-2J3TNJQT7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQMUCrh_kEX7eui0H_-Rvr2_IO5ywqoE',
    appId: '1:841967297444:android:391cc7743441b6ddf0d731',
    messagingSenderId: '841967297444',
    projectId: 'classic-18beb',
    storageBucket: 'classic-18beb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHITFLrl9Pa7fqWfQho1h1I4EIum9Xug',
    appId: '1:841967297444:ios:a95b64914c6828edf0d731',
    messagingSenderId: '841967297444',
    projectId: 'classic-18beb',
    storageBucket: 'classic-18beb.firebasestorage.app',
    iosClientId: '841967297444-uc3ddtfgpt1oh779iklh2np68n00k238.apps.googleusercontent.com',
    iosBundleId: 'com.example.kings',
  );

}